### ISSUE TITLE
Simplify control flow instructions

### ISSUE THREAD

**Issue by Robbepop** [Robbepop/runwell#13]
Today Runwell IR has many different control flow instructions. Among others those include:

- `BranchInstr`: An unconditional jump.
- `IfThenElse`: A conditional jump with 2 different destinations.
- `BrTable`: A branching table with N different destinations.

The `IfThenElse` control flow instruction is theoretically superseeded by the more powerful `BrTable` instruction.
This issue proposes to replace all uses of `IfThenElse` with `BrTable` instructions and to also rename the instructions to better reflect their purpose.

- `BranchInstr`: The name is actually fine.
- `BrTable`: Should be renamed to `MatchBranchInstr`.

Also there is the so-called `SelectInstr` which is similar to the `BrTable` in that it does different things depending on a selector value. Unlike the `MatchBranchInstr` it simply returns a selected SSA value. This issue proposes to unify both concepts by also renaming `SelectInstr` to `MatchSelectInstr`, allow `MatchSelectInstr` to have N instead of just 2 operands and also change their syntax to be more similar:

## MatchBranchInstr Syntax

```rust
match<S> selector {
    0 => branch bb0,
    1 => branch bb1(v1),
    2 => branch bb2(v0, v1),
    _ => branch bb1(v0),
}
```

## MatchSelectInstr Syntax

```rust
let result: R = match<i1, R> selector {
    false => v1,
    true  => v2,
}
```
or
```rust
let (result_1: R1, .., result_n: Rn) = match<i1, (R1, .., Rn)> selector {
    false => (v1_1, .., v1_n),
    true  => (v2_1, .., v2_n),
}
```
or
```rust
let result: R = match<S, R> selector {
    0 => v1,
    1 => v2,
    2 => v3,
    _ => v2,
}
```
or
```rust
let (result_1: R1, .., result_n: Rn) = match<S, (R1, .., Rn)> selector {
    0 => (v1_1, .., v1_n),
    1 => (v2_1, .., v2_n),
    ...
    _ => (vm_1, .., vm_n),
}
```

Where `selector` is the SSA value depicting the value to select the match arm, `S` represents the type of the `selector` and `R` and `R1`, .., `Rn` represents the type or tuple-type of the `result` values respectively.

## ToDo List

- [x] Implement `MatchSelectInstr`: https://github.com/Robbepop/runwell/issues/14
- [x] Add `InstructionBuilder::match_branch` constructor method.
- [x] Implement lowering from If-Then-Else to `MatchBranchInstr`.
- [x] Implement `VisitEdges` and `VisitEdgesMut` visitors similar to value visitors for instructions.
- [x] Rename `BrTable` to `MatchBranchInstr`
- [x] Resolve issues with `change_else_branch_target` method required for Wasm translation.
- [x] Remove deprecated If/Then/Else instruction.

**Comment by Robbepop** [comment]
Implemented by

- lower if to match: https://github.com/Robbepop/runwell/commit/7086253f8973b74da8f225e023ce18b8b94afb86
- add match branch instruction builder: https://github.com/Robbepop/runwell/commit/7f3ca26f7320b8af0dce1ab9e9b841ca7f7d50da
- refactor `change_jump_of_else`: https://github.com/Robbepop/runwell/commit/f850cbe1c86d05943ead1bcfce134dfa7fa87a9d
- remove `IfThenElseInstr`: https://github.com/Robbepop/runwell/commit/db68aecb20190822b6428d1e2a54a480d9a1b021

Closed.
