### ISSUE TITLE
Allow MatchSelectInstr to return multiple values

### ISSUE THREAD

**Issue by Robbepop** [Robbepop/runwell#14]
Currently after recent refactorings the `MatchSelectInstr` allows for an arbitrary number of match arms to select a resulting value.
However, a big limitation currently is that it only allows to return a single SSA value.
Generally Runwell IR allows for multiple return values of its instructions. So far only the variety of call instructions are using this to model multiple return values for functions.
However, the new `MatchSelectInstr` could profit immensely from being able to return multiple value and it would bring its power on a similar level as the branch table terminal instruction.

## ToDo

- [x] Do the thing. (Implement multi-value return `MatchSelectInstr`.)
- [x] Adjust the Runwell IR interpreter.
- [x] Adjust existing tests.
- [x] Create a `MatchSelectInstrBuilder` type that simplifies construction.
- [x] Write new tests for the complex internals of the new `MatchSelectInstr`.
- [x] Enable constructing multi-value returning `MatchSelectInstr` from within the `InstructionBuilder`.
- [x] Write interpreter test using a multi-returning `MatchSelectInstr`, e.g. `sort2` sorting 2 fixed numbers.

**Comment by Robbepop** [comment]
Implemented all ToDo items. Closed.

- Commit introducing the interpreter test: https://github.com/Robbepop/runwell/commit/cb7fff105b7bbb43b78346fbd12e435a5fb7a806
- Commit introducing InstructionBuilder API for match select with multiple return values: https://github.com/Robbepop/runwell/commit/6cefc48f44e4cbd267a3899a6603797efacc6564
